### PR TITLE
Add seconds converter helper

### PR DESCRIPTION
**Pull request by steffendsommer**
```swift
expirationPeriod: 3600, // 1 hour
```
becomes
```swift
expirationPeriod: 1.hoursInSecs,
```

### CODE REVIEW

**Comment by siemensikkema** [comment]
Although these extensions are helpful they do not always give the correct result. See the section on DateInterval in https://nshipster.com/timeinterval-date-dateinterval/

**Comment by steffendsommer** [comment]
@siemensikkema for the/our common use case I think this is sufficient. Basically we just want to be able to e.g. say: "This signer should expire after 30 days". Maybe it's a matter of just noting this as a comment if a consumer wants that level of precision. What do you think?

**Comment by siemensikkema** [comment]
Yeah I think for those use cases it is handy to have. But what about writing it like this?

```swift
public extension Numeric {
    public var minsInSecs: Self {
        return self * 60
    }

    public var hoursInSecs: Self {
        return minsInSecs * 60
    }

    public var daysInSecs: Self {
        return hoursInSecs * 24
    }

    public var weeksInSecs: Self {
        return daysInSecs * 7
    }
}
```

**Review by siemensikkema — APPROVED** [review]

**Comment by steffendsommer** [comment]
@siemensikkema much better - thanks 👍

**Pull request merged**
